<<<<<<< HEAD
# Jekyll configuration

name: Xixia
description: Welcome to Xixiaï¼

# url is currently only used only for the RSS feed in feed.xml
url: https://github.com/qibancom/helloworld

# baseurl will often be '', but for a project page on gh-pages, it needs to
# be the project name.
# *** IMPORTANT: If your local "jekyll serve" throws errors change this to '' or
#     run it like so: jekyll serve --baseurl=''
baseurl: '/helloworld'
## default date_format
date_format: 
  title: "%B-%-d-%Y"
  archive: "%b"
  categories: "%b-%Y"
  tag: "%b-%Y"
# Language
lan: "en" 

paginate: 10

highlighter: rouge
markdown: kramdown
gems: ['jekyll-paginate']

exclude: ['README.md', 'LICENSE', "*.bak"]
=======
theme: jekyll-theme-time-machine
>>>>>>> 4484f21888450df61d0a9a35374fe93e49189fe5
